export const resultData = [
    {
        serviceName: "EC2",
        serviceImg: "/serviceImages/EC2.png",
        tags: ["#需要我隨時都在", "#適應性強", "#默默付出"],
        soulMate: "ELB",
        soulMateImg: "/serviceImages/IAM.png",
        friends: "Lambda",
        friendsImg: "/serviceImages/ELB.png",
        work_describe: "能迅速掌握新技能，並根據工作需求快速調整自己的步伐。你在面對高強度的工作壓力時，能夠全力以赴，展現出卓越的高效率。無論是處理複雜的項目還是應對緊急情況，你總是能夠迎刃而解。",
        life_describe: "是個適應性強且能夠靈活的人，能夠根據環境的變化迅速調整自己的步伐。擁有強大的能力，可以在需要的時候全力以赴，也可以在平靜時輕鬆應對。是朋友們背後最堅強的後盾喔！",
        service_describe: "Amazon Elastic Compute Cloud (Amazon EC2) 提供最廣泛、最深入的運算平台，擁有超過 750 個執行個體，可選擇最新處理器、儲存、聯網、作業系統和購買模型，以協助您最有效地滿足工作負載需求。",
        service_link: "https://aws.amazon.com/tw/ec2/"
    },
    {
        serviceName: "S3",
        serviceImg: "/serviceImages/S3.png",
        tags: ["#我記得你說過", "#我懂你", "#超會給情緒價值"],
        soulMate: "Cloudwatch",
        soulMateImg: "/serviceImages/Cloudwatch.png",
        friends: "DynamoDB",
        friendsImg: "/serviceImages/DynamoDB.png",
        work_describe: "團隊中的數據管理專家，能夠記住並快速檢索大量的數據和信息，確保團隊在需要時能夠立即獲得所需的資料。你非常可靠，無論是文件、報告、還是歷史數據，都能夠完好無損地保存並準確地提供。",
        life_describe: "你是朋友們接收情緒的垃圾桶，朋友們都依賴您傾訴心事，並得到安慰和支持。你能夠提供極高的情緒價值，總能記得周遭朋友們的所有細節與各種小事，讓人感到被重視。",
        service_describe: "Amazon Simple Storage Service (Amazon S3) 是一種物件儲存服務，具備高可擴展性、資料可用性、安全性和效能，可以存放和保護幾乎任何使用案例的任何資料量。",
        service_link: "https://aws.amazon.com/tw/s3/"
    },
    {
        serviceName: "Lambda",
        serviceImg: "/serviceImages/Lambda.png",
        tags: ["#職場強人", "#沒事別找我", "#超絕T人"],
        soulMate: "API gateway",
        soulMateImg: "/serviceImages/API gateway.png",
        friends: "EC2",
        friendsImg: "/serviceImages/EC2.png",
        work_describe: "高效的實行者和解決問題者。當面臨緊急情況或突發事件時，能迅速調整工作優先級，並立即採取行動。你不是在下班後會和同事們喝杯小酒的人，但你的工作風格使得團隊能夠快速適應變化，並達成目標。",
        life_describe: "個性中充滿了動感和效率，你的行為有時會顯得急促，有時稍微停下腳步看看風景也很不錯！你喜歡變化和挑戰，總能在不斷變化的環境中保持動力和積極，不喜歡浪費時間在沒意義的事上。",
        service_describe: "AWS Lambda 是一種運算服務，可執行程式碼以回應事件並自動管理運算資源，使其成為將想法轉化為現代生產無伺服器應用程式最快捷的方式。",
        service_link: "https://aws.amazon.com/tw/lambda/"
    },
    {
        serviceName: "Cloudwatch",
        serviceImg: "/serviceImages/Cloudwatch.png",
        tags: ["#控制狂", "#敏銳的嗅覺", "#細節怪"],
        soulMate: "EC2",
        soulMateImg: "/serviceImages/EC2.png",
        friends: "IAM",
        friendsImg: "/serviceImages/IAM.png",
        work_describe: "可靠的監督者。你擅長掌握團隊的狀況，確保專案按照計劃推進。在面對突發情況時，你會反覆檢查相關的信息，確保所有細節都得到妥善處理，你能夠提供準確的信息和建議，確保工作流程的順暢和高效。",
        life_describe: "你也許話不多，但對周遭的動態有深刻的洞察，總是默默的幫助身邊的朋友。在事情發生前會在腦中演練很多次，有時候會過度焦慮，希望能夠掌握所有資訊！",
        service_describe: "Amazon Cloudwatch 是一項服務，可監控應用程式、回應效能變更、最佳化資源使用，並提供有關營運狀況的見解。",
        service_link: "https://aws.amazon.com/tw/cloudwatch/"
    },
    {
        serviceName: "DynamoDB",
        serviceImg: "/serviceImages/DynamoDB.png",
        tags: ["#整理魔人", "#我馬上完成", "#朋友王"],
        soulMate: "Lambda",
        soulMateImg: "/serviceImages/Lambda.png",
        friends: "Cloudwatch",
        friendsImg: "/serviceImages/Cloudwatch.png",
        work_describe: "你就像反應靈敏、多才多藝的秘書。無論被交付多麼龐大的資料量，或是相當複雜的要求，你都能在極短的時間內給予對方精準的回應。此外，你還非常謙虛，總是默默地在背後支持著團隊。",
        life_describe: "總是能保持冷靜、穩定，即使面對突發狀況，也能迅速做出反應。平時喜歡打掃家裡，從不會有找不到東西的情況發生。朋友多，與每個人都相處融洽。",
        service_describe: "Amazon DynamoDB 是無伺服器的 NoSQL 資料庫服務，能讓您開發任何規模的現代應用程式，作為無伺服器資料庫。",
        service_link: "https://aws.amazon.com/tw/dynamodb/"
    },
    {
        serviceName: "IAM",
        serviceImg: "/serviceImages/IAM.png",
        tags: ["#重視Me Time", "#我有我的原則", "#沒事別約我"],
        soulMate: "S3",
        soulMateImg: "/serviceImages/S3.png",
        friends: "Cloudwatch",
        friendsImg: "/serviceImages/Cloudwatch.png",
        work_describe: "做事非常講求條理與規矩的人。你總是公事公辦，嚴格按照規範和流程來完成每一項任務，確保所有的節奏都在你的嚴密控制之下。你注重細節，堅持所有操作都符合標準和安全要求，不容許任何偏差。",
        life_describe: "非常講究秩序，喜歡按照既定的規範和方法來做事，不喜歡隨意改變計劃，對自己的行為和承諾負責，為周圍的人帶來安全感和信任感。",
        service_describe:"藉助 AWS Identity and Access Management (IAM)，您可以指定誰或者哪些服務可以存取 AWS 中的服務和資源，集中管理精細的許可，並分析存取權以最佳化整個 AWS 的許可。",
        service_link: "https://aws.amazon.com/tw/iam/"
    },
    {
        serviceName: "API gateway",
        serviceImg: "/serviceImages/API gateway.png",
        tags: ["#渣男辨識器", "#先冷靜談談好嗎", "#情報中心"],
        soulMate: "Lambda",
        soulMateImg: "/serviceImages/Lambda.png",
        friends: "DynamoDB",
        friendsImg: "/serviceImages/DynamoDB.png",
        work_describe: "這樣的人在工作中扮演著至關重要的角色。你們擅長溝通與調解，能夠有效地在不同部門或團隊之間建立清晰的對話橋樑。你們的敏銳性使你們能夠準確洞察潛在的風險，並及時采取措施進行防範，避免不必要的損失。",
        life_describe: "你擅長溝通與調解，能夠有效地協調人之間的需求和交流。然而，您內心卻防備心重，難以完全放下心防，對於人事物的善惡分辨非常敏銳。",
        service_describe:"Amazon API Gateway 是一種全受管的服務，可讓開發人員輕鬆地建立、發佈、維護、監控和保護任何規模的 API。API 可作為應用程式的「前門」，以便從後端服務存取資料、商業邏輯或功能。",
        service_link: "https://aws.amazon.com/tw/api-gateway/"
    },
    {
        serviceName: "ELB",
        serviceImg: "/serviceImages/ELB.png",
        tags: ["#天生leader", "#無法放鬆", "#我相信你可以的！"],
        soulMate: "EC2",
        soulMateImg: "/serviceImages/EC2.png",
        friends: "Lambda",
        friendsImg: "/serviceImages/Lambda.png",
        work_describe: "就像是團隊中的指揮官，時常擔任調度和領導的角色。你擅長將工作合理地指派給那些目前沒有忙碌的成員，確保每個人都能充分發揮作用。無論工作量如何變化，你總能靈活調整分配策略，避免過載並保持整體效率。",
        life_describe: "你有著卓越的組織能力和敏銳的洞察力，能夠察覺每個人的需求和狀況，你的主動性和負責任的態度讓你在朋友中擁有極高的威望。",
        service_describe:"Elastic Load Balancing (ELB) 會自動將傳入的應用程式流量分配在一個或多個可用區域 (AZ) 中的多個目標和虛擬設備上。",
        service_link: "https://aws.amazon.com/tw/elasticloadbalancing/"
    }
];